save_loc: '/glade/derecho/scratch/schreck/smoke_test_v2_025deg'
seed: 1000

data:
    source:
        ERA5:
            level_coord: "level"
            levels: [25.5, 75.0, 125.0, 175.0, 225.0, 275.0, 350.0, 450.0, 550.0, 650.0, 775.0, 887.5, 962.5]
            variables:
                prognostic:
                    vars_3D: ['U', 'V', 'T', 'specific_total_water']
                    vars_2D: ['SP', 'VAR_2T', 'VAR_10U', 'VAR_10V']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                diagnostic:
                    vars_2D: ['total_precipitation', 'evaporation', 'top_net_thermal_radiation', 'top_net_solar_radiation',
                              'surface_latent_heat_flux', 'surface_net_solar_radiation',
                              'surface_net_thermal_radiation', 'surface_sensible_heat_flux']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                dynamic_forcing:
                    vars_2D: ['toa_incident_solar_radiation', 'land_sea_CI_mask']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                static:
                    vars_2D: ['z_norm', 'land_sea_mask']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/static/ERA5_plevel_6h_static.zarr'

    start_datetime: "2021-06-01"
    end_datetime: "2021-07-01"
    timestep: "6h"
    history_len: 1
    forecast_len: 1
    one_shot: True
    lead_time_periods: 6
    skip_periods: null
    static_first: True
    scaler_type: 'std_new'

    mean_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/mean_std/mean_6h_1979_2019_13lev_0.25deg.nc'
    std_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/mean_std/std_6h_1979_2019_13lev_0.25deg.nc'

data_valid:
    source:
        ERA5:
            level_coord: "level"
            levels: [25.5, 75.0, 125.0, 175.0, 225.0, 275.0, 350.0, 450.0, 550.0, 650.0, 775.0, 887.5, 962.5]
            variables:
                prognostic:
                    vars_3D: ['U', 'V', 'T', 'specific_total_water']
                    vars_2D: ['SP', 'VAR_2T', 'VAR_10U', 'VAR_10V']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                diagnostic:
                    vars_2D: ['total_precipitation', 'evaporation', 'top_net_thermal_radiation', 'top_net_solar_radiation',
                              'surface_latent_heat_flux', 'surface_net_solar_radiation',
                              'surface_net_thermal_radiation', 'surface_sensible_heat_flux']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                dynamic_forcing:
                    vars_2D: ['toa_incident_solar_radiation', 'land_sea_CI_mask']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/all_in_one/ERA5_plevel_6h_*.zarr'
                static:
                    vars_2D: ['z_norm', 'land_sea_mask']
                    path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/static/ERA5_plevel_6h_static.zarr'

    start_datetime: "2021-07-01"
    end_datetime: "2021-08-01"
    timestep: "6h"
    history_len: 1
    forecast_len: 1
    one_shot: True
    lead_time_periods: 6
    skip_periods: null
    static_first: True
    scaler_type: 'std_new'

    mean_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/mean_std/mean_6h_1979_2019_13lev_0.25deg.nc'
    std_path: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/mean_std/std_6h_1979_2019_13lev_0.25deg.nc'

trainer:
    type: era5-v2
    mode: none
    cpu_offload: False
    activation_checkpoint: False

    load_weights: False
    load_optimizer: False
    load_scaler: False
    load_scheduler: False

    skip_validation: False
    update_learning_rate: False

    save_backup_weights: False
    save_best_weights: False

    learning_rate: 1.0e-04
    weight_decay: 0

    train_batch_size: 1
    valid_batch_size: 1

    batches_per_epoch: 5
    valid_batches_per_epoch: 2
    stopping_patience: 999

    start_epoch: 0
    num_epoch: 2
    reload_epoch: False
    epochs: &epochs 2

    use_ema: False
    use_scheduler: False

    amp: False
    grad_accum_every: 1
    grad_max_norm: 1.0

    thread_workers: 0
    valid_thread_workers: 0

model:
    type: "crossformer"
    frames: 1
    image_height: 721
    image_width: 1440
    levels: 13
    channels: 4
    surface_channels: 4
    input_only_channels: 4
    output_only_channels: 8

    patch_width: 1
    patch_height: 1
    frame_patch_size: 1

    dim: [32, 64, 128, 256]
    depth: [2, 2, 2, 2]
    # 721+80=801 -> floor/2 -> 400 (=10×40), 1440+160=1600 -> /2 -> 800 (=10×80)
    global_window_size: [10, 5, 2, 1]
    local_window_size: 10
    cross_embed_kernel_sizes:
    - [4, 8, 16, 32]
    - [2, 4]
    - [2, 4]
    - [2, 4]
    cross_embed_strides: [2, 2, 2, 2]
    attn_dropout: 0.
    ff_dropout: 0.

    interp: True
    use_spectral_norm: True

    padding_conf:
        activate: True
        mode: earth
        pad_lat: [40, 40]
        pad_lon: [80, 80]

    post_conf:
        activate: False

loss:
    training_loss: "mse"
    validation_loss: "mse"
    use_power_loss: False
    use_spectral_loss: False
    use_latitude_weights: False
    latitude_weights: '/glade/campaign/cisl/aiml/ksha/CREDIT_data/ERA5_plevel_base/static/ERA5_plevel_6h_static.zarr'
    use_variable_weights: False
