save_loc: '/glade/derecho/scratch/$USER/CREDIT/weatherbench2'
seed: 31415

data:
  source:
    WBERA5:
      dataset_type: "weatherbench2_era5"
      resolution: "240x121"   # optional; overridden by the resolution kwarg
      level_coord: "level"
      levels: [500, 850]
      variables:
        prognostic:
          vars_3D: ["temperature", "specific_humidity"]
          vars_2D: ["surface_pressure", "2m_temperature"]
        diagnostic:
          vars_2D: ['total_precipitation_6hr']
        dynamic_forcing:
          vars_2D: ["sea_surface_temperature"]
        static:
          vars_2D: ["land_sea_mask", "geopotential_at_surface"]
  start_datetime: "1979-01-01"
  end_datetime: "2017-12-31 18:00:00"
  timestep: "6h"

  history_len: 1
  forecast_len: 1

preblocks:
  per_step:
    log_transform:
      type: "log_transform"
      args:
        variables:
          - 'WBERA5/prognostic/3d/specific_humidity'
          - "WBERA5/prognostic/2d/surface_pressure"
          - "WBERA5/diagnostic/2d/total_precipitation_6hr"
        data_types:
          - 'input'
          - 'target'
    fill_values:
      type: "fill_values"
      args:
        rules:
          - search: nan
            fill: 0.0
        variables: []
        data_types:
          - 'input'
          - 'target'
    scaler:
      type: "bridgescaler_transform"
      args:
        variables: []
        scaler_path: "/glade/derecho/scratch/$USER/CREDIT/weatherbench2/scaler.json"
        scaler_type: "quantile"
        scaler_params:
          channels_last: False
          compression: 500

    vars_concat:
      type: "concat"

trainer:
  mode: none
  train_batch_size: 2
  batches_per_epoch: 3  # 0 means use all data
  thread_workers: 4
  prefetch_factor: 2

pbs:
  # Casper
  conda: "credit-casper"
  project: "NAML0001"
  job_name: "credit_preprocess"
  walltime: "04:00:00"
  ngpus: 1
  ncpus: 8
  mem: "128GB"
  queue: "casper"
  gpu_type: "a100_80gb"

  # Derecho (uncomment and comment out Casper block above to use)
  # conda: "credit-derecho"
  # project: "NAML0001"
  # job_name: "credit_preprocess"
  # walltime: "04:00:00"
  # ngpus: 4
  # ncpus: 64
  # mem: "480GB"
  # queue: "main"




