name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{matrix.python-version}}
          cache: 'pip'
    #  - name: ESMF support Package Install
    #    run: |
    #      sudo apt-get -qq -y update
    #      sudo apt -qq install libnetcdf-dev libnetcdff-dev
    #  - name: Install ESMF
    #    uses: esmf-org/install-esmf-action@39afafec8570201bcf14ccdba7ffc246278f8d21 # v1.0.2
    #    env:
    #      ESMF_NETCDF: nc-config
    #    with:
    #      version: 8.9.1
    #      esmpy: true
    #      cache: false
    #  - name: Print ESMF Info
    #    run: |
    #      cat ${ESMFMKFILE}
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip 
          pip install uv
          uv pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu --system
          uv pip install ".[develop]" --system
          uv pip install pytest pytest-cov --system
    #      pip install xesmf
      - name: Run tests
        run: |
          pytest --cov=credit --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
            env_vars: PYTHON
            token: ${{ secrets.CODECOV_TOKEN }}

